/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonsItem: typeof import('./src/components/ButtonsItem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    PannelItem: typeof import('./src/components/PannelItem.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
