/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ButtonsItem: typeof import('./components/ButtonsItem.vue')['default']
    copy: typeof import('./components/WelcomeItem copy.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    IEpArrowDownBold: typeof import('~icons/ep/arrow-down-bold')['default']
    IEpArrowUpBold: typeof import('~icons/ep/arrow-up-bold')['default']
    IEpBell: typeof import('~icons/ep/bell')['default']
    IEpBellFilled: typeof import('~icons/ep/bell-filled')['default']
    IEpBottom: typeof import('~icons/ep/bottom')['default']
    IEpCaretLeft: typeof import('~icons/ep/caret-left')['default']
    IEpCaretRight: typeof import('~icons/ep/caret-right')['default']
    IEpTop: typeof import('~icons/ep/top')['default']
    IEpWarningFilled: typeof import('~icons/ep/warning-filled')['default']
    OutButtons: typeof import('./components/OutButtons.vue')['default']
    PannelItem: typeof import('./components/PannelItem.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
